### ISSUE TITLE
live demo pages yield "502 bad gateway"

### ISSUE THREAD

**Issue by gernotstarke** [stefanrinderle/sonar-softvis3d-plugin#4]
e.g. http://softvis3d.com/sonar/plugins/resource/38581?page=SoftVis3D

(Platform: MacOS 10.11, Chrome, latest)

**Comment by stefanrinderle** [comment]
Server was down - sorry for that. Should work now!

**Comment by gernotstarke** [comment]
thx for the quick fix. #impressed!!
